### ISSUE TITLE
`pacstall --upgrade` gets permission denied

### ISSUE THREAD

**Issue by saenai255** [pacstall/pacstall#463]
**Describe the bug**
Pacstall `upgrade` fails to verify packages

**To Reproduce**
1. Have the following repositories added
```
https://raw.githubusercontent.com/pacstall/pacstall-programs/master
https://raw.githubusercontent.com/paulcosma97/pacstall-programs/master
https://raw.githubusercontent.com/Henryws/pacstall-programs/exa
```
2. Install `balena-etcher-electron-deb`, `exa-git` & `shfmt-bin`
3. Run `pacstall --upgrade`

**Expected behavior**
Pacstall should have permissions to check for updates

**Screenshots**
![image](https://user-images.githubusercontent.com/16655260/149666805-38371a85-54b7-47f6-a82f-5da4f968bc5f.png)

**Desktop (please complete the following information):**

- Pop!_OS 21.10
- 1.7 Sienna

**Comment by Henryws** [comment]
Fixed with https://github.com/pacstall/pacstall/pull/447

Update to 1.7.1 develop for the fix

**Comment by saenai255** [comment]
The error message is gone but the issue remains
![image](https://user-images.githubusercontent.com/16655260/149667089-fc28234b-a3f6-4a96-acc1-58b136b5c9c6.png)
